### ISSUE TITLE
ncurses.h: No such file or directory

### ISSUE THREAD

**Issue by Kreiseljustus** [nobuh/napple1#3]
Cant find the header file anywhere?

**Comment by nobuh** [comment]
Thanks report this!.  I'm sorry the documentation has not been update for so long. Many things has changed.

If you use Windows, please considier using WSL2 and installing Ubuntu 18.04 on top of it.

And then please install gcc, make and libncursers-dev by `sudo apt install gcc make libncurses-dev` 

If you use newer gcc, for example gcc 11.3.0 on Ubuntu 22.04, I see another error around global variable diffinitions. I have to need to check it...

**Comment by nobuh** [comment]
#4 and #5 fix the install instruction in README and some gcc errors. 
If you find another issue, please let me know. 
I'd like to close this.
