### ISSUE TITLE
Add a way to automate keyboard input

### ISSUE THREAD

**Issue by fstark** [nobuh/napple1#6]
It is difficult to bring data into an Apple1, short of typing everything. Copy/paste doesn't work as the terminal is not aware of the keyboard status register.

Add a feature that let the user select a file and have it typed on the keyboard.

If such feature is of interest, I will submit a design and a patch.

(note: I implemented a very crude version of it in my fork https://github.com/fstark/napple1 . Typing 'Shift-K' makes the emulator type-in the content of the "KBD.TXT" file).

**Comment by nobuh** [comment]
Hi, thanks for the issue 

> This have been done to be able to load basic programs and use the 'dump"
features to transfer them to binary files.

Sounds good! If it is possible, I'm happy the name of input file could be AUTOTYPING.TXT or something around typing words.

**Comment by fstark** [comment]
Sure I'll look at that over the week-end and submit a first version of a patch.

**Comment by fstark** [comment]
Sent pull request #7 with the changes. Hopefully it matches the style and architecture of the rest.

**Comment by nobuh** [comment]
Merged
