### ISSUE TITLE
Commands in autotyping proposal

### ISSUE THREAD

**Issue by fstark** [nobuh/napple1#9]
This feature suggestion is probably a bit more controversial:

As the apple1 has no TAB key, I added macro-commands in the AUTOTYPING.TXT file. For instance, the 'F' command switches to "fast" mode, and is invoked like:

```
<TAB>F
00.7F
<TAB>F
```

This will dump the content of the 00.7F memory space instantaneously.

Current commands are mirroring a subset of the existing commands:

* 'B' for Basic
* 'Dfile' to dump core into 'file'
* 'F' fast mode switch (too fragile, should probably be 'F' and 'S', or 'F0' and 'F1', or 'Fon' and 'Foff'
* 'M' for 8K/32K mode (too fragile, should probably be 'M8' and 'M32')
* 'Q' to quit

Typically, I would do things like:

```
<TAB>FB
10 PRINT "HELLO, WORLD."
20 GOTO 10
<TAB>Dsample
<TAB>Q
```

To capture a core containing the above BASIC program tokenized.

The changes are a bit more intrusive than earlier patch, as the current code of napple1 has a tendency to try to communicate with the end-user from within core functions.

This is very useful to me, I will maintain a branch but will make the work to port it to the trunk and document it correctly if you think it is broadly useful.

**Comment by fstark** [comment]
I am realizing that I am dragging napple1 in a direction that may not the one you want. I have already added plenty of additional stuff, mostly geared at making development of software for real apple1 easier, with little regards to user experience, performance, realism or backward compatibility.
I am closing this, I will list the differences between versions in the forked page fstark/napple1.

**Comment by fstark** [comment]
(forgot to close)

**Comment by nobuh** [comment]
I think your original commands is great feature for real educational purposes.

napple1 is a just for fun toy project and I'm happy your fstark/napple1 progress.
